### ISSUE TITLE
storage backends without path access not supported

### ISSUE THREAD

**Issue by smcoll** [jazzband/django-silk#208]
If an S3 storage backend, for example, is used as `SILKY_STORAGE_CLASS`, a `NotImplementedError` is raised when trying to save the file.

```
silk.profiling.profiler [ERROR] [profiler:__exit__] Exception when performing meta profiling, dumping trace below
Traceback (most recent call last):
  File "/home/myenv/lib/python3.5/site-packages/silk/middleware.py", line 117, in _process_response
    collector.finalise()
  File "/home/myenv/lib.python3.5/site-packages/silk/collector.py", line 156, in finalise
    with open(self.request.prof_file.storage.path(file_name), 'w+b') as f:
  File "/home/me/.pyenv/versions/evidencecare3/lib/python3.5/site-packages/django/core/files/storage.py", line 111, in path
    raise NotImplementedError("This backend doesn't support absolute paths.")
NotImplementedError: This backend doesn't support absolute paths.
```

**Comment by vladox** [comment]
How did you solve this issue?
