### ISSUE TITLE
silk_clear_request_log fails on Postgres

### ISSUE THREAD

**Issue by devmonkey22** [jazzband/django-silk#290]
django-silk==3.0.0

The SQL executed to clear the request logs fail with multiple errors on Postgres 9.5.12.

The errors include:

- django.db.utils.ProgrammingError: syntax error at or near "'silk_profile'" LINE 1: ALTER TABLE 'silk_profile' DISABLE TRIGGER ALL;
    -  Postgres needs unquoted or double quotes, but was given single quotes.
- django.db.utils.NotSupportedError: cannot truncate a table referenced in a foreign key constraint DETAIL:  Table "silk_profile_queries" references "silk_profile". HINT:  Truncate table "silk_profile_queries" at the same time, or use TRUNCATE ... CASCADE.

These seem to stem from changes for PR #270. 

```
Traceback (most recent call last):
  File "oc/manage.py", line 18, in <module>
    main()
  File "oc/manage.py", line 15, in main
    execute_from_command_line(sys.argv)
  File "/home/user/dev/oc/ENV/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/user/dev/oc/ENV/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/dev/oc/ENV/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/dev/oc/ENV/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/user/dev/oc/ENV/local/lib/python2.7/site-packages/silk/management/commands/silk_clear_request_log.py", line 41, in handle
    Command.delete_model(silk.models.Profile)
  File "/home/user/dev/oc/ENV/local/lib/python2.7/site-packages/silk/management/commands/silk_clear_request_log.py", line 21, in delete_model
    cursor.execute("ALTER TABLE %s DISABLE TRIGGER ALL;", [table])
  File "/home/user/dev/oc/ENV/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/user/dev/oc/ENV/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/user/dev/oc/ENV/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/user/dev/oc/ENV/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: syntax error at or near "'silk_profile'"
LINE 1: ALTER TABLE 'silk_profile' DISABLE TRIGGER ALL;
```

**Comment by arjenfvellinga** [comment]
I'm using 3.0.1 and `silk_clear_request_log` still fails for me on Postgres with (an other) programming error:

`
django.db.utils.ProgrammingError: permission denied: "RI_ConstraintTrigger_a_7428263" is a system trigger
`

**Comment by gforcada** [comment]
The same happens to me like @arjenfvellinga do we need to change the database user to an admin for clearing data? :thinking:

**Comment by gforcada** [comment]
I manually changed on lines 23 and 25:

https://github.com/jazzband/django-silk/blob/639da91e61973268efe885ecc5524185748da762/silk/management/commands/silk_clear_request_log.py#L23

https://github.com/jazzband/django-silk/blob/639da91e61973268efe885ecc5524185748da762/silk/management/commands/silk_clear_request_log.py#L25

the ``ALL`` for ``USER`` and the command was successful. I will write a pull request for it.

**Comment by mOscuro** [comment]
Hi! any news about a possible release? I'm getting impacted by this as well. Thanks!

**Comment by mOscuro** [comment]
Hi! any news about a possible release? I'm getting impacted by this as well. Thanks!

**Comment by mOscuro** [comment]
Hi! any news about a possible release? I'm getting impacted by this as well. Thanks!

**Comment by betoborda** [comment]
It looks like this error is still happening on the latest version (django-silk 3.0.1 ) from pypi released: Jul 3, 2018.  When do you plan to release a new version?

**Comment by guy881** [comment]
We had the same problem and we cleared the data by rolling back migrations of this app `python manage.py migrate silk zero`.

**Comment by davidcorbin** [comment]
Still having the issue referenced by @arjenfvellinga above with Postgres

**Comment by pptime** [comment]
Yes, if a release is planned, that could be wonderful
