### ISSUE TITLE
Upgrade to Python 3: migrations broken

### ISSUE THREAD

**Issue by florianm** [jazzband/django-silk#297]
### Problem
Upgrading a Django project to Python 3 and Django 2: ./manage.py migrate falls over a bytestring:
Note I've hand-inserted a print() statement into $VIRTUAL_ENV/lib/python3.6/site-packages/django/db/models/manager.py
```
Model <class '__fake__.Site'>, name b'objects' # print from django.db.models.manager

Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "$VIRTUAL_ENV/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "$VIRTUAL_ENV/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "$VIRTUAL_ENV/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "$VIRTUAL_ENV/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "$VIRTUAL_ENV/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 160, in handle
    pre_migrate_apps = pre_migrate_state.apps
  File "$VIRTUAL_ENV/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "$VIRTUAL_ENV/lib/python3.6/site-packages/django/db/migrations/state.py", line 210, in apps
    return StateApps(self.real_apps, self.models)
  File "$VIRTUAL_ENV/lib/python3.6/site-packages/django/db/migrations/state.py", line 271, in __init__
    self.render_multiple(list(models.values()) + self.real_models)
  File "$VIRTUAL_ENV/lib/python3.6/site-packages/django/db/migrations/state.py", line 306, in render_multiple
    model.render(self)
  File "$VIRTUAL_ENV/lib/python3.6/site-packages/django/db/migrations/state.py", line 575, in render
    return type(self.name, bases, body)
  File "$VIRTUAL_ENV/lib/python3.6/site-packages/django/db/models/base.py", line 152, in __new__
    new_class.add_to_class(obj_name, obj)
  File "$VIRTUAL_ENV/lib/python3.6/site-packages/django/db/models/base.py", line 315, in add_to_class
    value.contribute_to_class(cls, name)
  File "$VIRTUAL_ENV/lib/python3.6/site-packages/django/db/models/manager.py", line 117, in contribute_to_class
    setattr(model, name, ManagerDescriptor(self))
TypeError: attribute name must be string, not 'bytes'
```

### Cause
There is a stray bytestring (`b''`) in migration 0003. 
All migrations are parsed, even if they already have been applied, so Django will trip over any bytestring.
Since unicode_literals are imported (and the string in question is empty anyways), it should be safe to drop the `b` prefix.

**Comment by avelis** [comment]
@florianm If you want to create a PR I would be happy to take a look and merge it in.

**Comment by xrmx** [comment]
Looks like this has been fixed and the issue can be closed.
