### ISSUE TITLE
"DISTINCT ON fields is not supported by this database backend"

### ISSUE THREAD

**Issue by meequz** [jazzband/django-silk#311]
When I open my custom admin page using sqlite3 as DB, I got the error "DISTINCT ON fields is not supported by this database backend". Django v1.11.13, django-silk v3.0.1. Here is the traceback:

```
Internal Server Error: /admin/custom_page/
Traceback (most recent call last):
  File "/home/user/project/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/user/project/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/user/project/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/project/env/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/project/env/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/user/project/env/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/user/project/env/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/user/project/env/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/project/my-web-application/mwa/my_app/views.py", line 119, in get
    attributes = [obj.attribute for obj in db_objects]
  File "/home/user/project/env/lib/python3.5/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/home/user/project/env/lib/python3.5/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/user/project/env/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/home/user/project/env/lib/python3.5/site-packages/silk/sql.py", line 24, in execute_sql
    q, params = self.as_sql()
  File "/home/user/project/env/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 447, in as_sql
    result.append(self.connection.ops.distinct_sql(distinct_fields))
  File "/home/user/project/env/lib/python3.5/site-packages/django/db/backends/base/operations.py", line 156, in distinct_sql
    raise NotImplementedError('DISTINCT ON fields is not supported by this database backend')
NotImplementedError: DISTINCT ON fields is not supported by this database backend
[22/Oct/2018 07:39:41] "GET /admin/custom_page/ HTTP/1.1" 500 133698
```

My database settings:
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'mwa.sqlite3',
    }
}
```

There are no such issues when using PostgreSQL

**Comment by ritiksoni00** [comment]
it's late but 


as Django docs say `distinct()` is only supported by PostgreSQL.

**Comment by SebCorbin** [comment]
This is not an error with silk but rather with your code (i.e. `/home/user/project/my-web-application/mwa/my_app/views.py`)
