### ISSUE TITLE
integration with spyne

### ISSUE THREAD

**Issue by andreasssm** [jazzband/django-silk#329]
I am already using spyne-RPC as a SOAP server. I have installed django-silk to monitor requests. For my GET requests it works ok but when i POST i get the error below and a timeout. If I remove django-silk it works ok.
```
Traceback (most recent call last):
  File "/home/test/django/django-apps/venv-insolvency/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/test/django/django-apps/venv-insolvency/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/test/django/django-apps/venv-insolvency/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/test/django/django-apps/venv-insolvency/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/test/django/django-apps/venv-insolvency/lib/python2.7/site-packages/spyne/server/django.py", line 89, in __call__
    response = WsgiApplication.__call__(self, environ, start_response)
  File "/home/test/django/django-apps/venv-insolvency/lib/python2.7/site-packages/spyne/server/wsgi.py", line 304, in __call__
    return self.handle_rpc(req_env, start_response)
  File "/home/test/django/django-apps/venv-insolvency/lib/python2.7/site-packages/spyne/server/wsgi.py", line 411, in handle_rpc
    contexts = self.generate_contexts(initial_ctx, in_string_charset)
  File "/home/test/django/django-apps/venv-insolvency/lib/python2.7/site-packages/spyne/server/_base.py", line 64, in generate_contexts
    self.app.in_protocol.create_in_document(ctx, in_string_charset)
  File "/home/test/django/django-apps/venv-insolvency/lib/python2.7/site-packages/spyne/protocol/soap/soap11.py", line 202, in create_in_document
    charset)
  File "/home/test/django/django-apps/venv-insolvency/lib/python2.7/site-packages/spyne/protocol/soap/soap11.py", line 96, in _parse_xml_string
    chunk = next(xml_string)
StopIteration
```

**Comment by auvipy** [comment]
I am not sure, if spyne is a django project or app at all? which framework it is using under the hood? if any at all? I used spyne long.

**Comment by JeissonArcadio778** [comment]
¿Qué alternativas hay para esto?
