### ISSUE TITLE
Request with list in body causes '_mask_credentials' to fail

### ISSUE THREAD

**Issue by claradaia** [jazzband/django-silk#348]
Hello, me again. I added the session and auth middleware back and now the interface works. However, the silk middleware itself fails when I try to use certain views which receive **lists** on the request body. This is the error:

```
Traceback (most recent call last):
  ...
  File "/usr/local/lib/python3.6/site-packages/silk/middleware.py", line 64, in __call__
    self.process_request(request)
  File "/usr/local/lib/python3.6/site-packages/silk/middleware.py", line 107, in process_request
    request_model = RequestModelFactory(request).construct_request_model()
  File "/usr/local/lib/python3.6/site-packages/silk/model_factory.py", line 207, in construct_request_model
    body, raw_body = self.body()
  File "/usr/local/lib/python3.6/site-packages/silk/model_factory.py", line 186, in body
    body = self._mask_credentials(body)
  File "/usr/local/lib/python3.6/site-packages/silk/model_factory.py", line 109, in _mask_credentials
    if pattern.search(key):
TypeError: expected string or bytes-like object
```

I believe the problem is:

```
     def _mask_credentials(self, body):
         """
         Mask credentials of potentially sensitive info before saving to db.
         """
         try:
             **json_body = json.loads(body)   # works because a list is valid json**
         except Exception as e:
            ...
         else:
             pattern = re.compile(r'username|api|token|key|secret|password|signature', re.I)
             CLEANSED_SUBSTITUTE = '********************'
             **for key in json_body:  # key will actually be an item of the list**
                 if pattern.search(key):
                     json_body[key] = CLEANSED_SUBSTITUTE
             body = json.dumps(json_body)
         return body
```

Seems to me the easiest fix would be to try and pass for TypeErrors. Something more robust could be done iterating through the list and checking each item, but I find it hard to imagine someone would actually send a list of dicts _with credentials_.

**Comment by MichalSe** [comment]
Is there any update on this? Im getting this error too, using django rest framework - it fails saying the key (body - dictionary of attributes) is failing due to TypeError: expected string or bytes-like object

**Comment by Jorl17** [comment]
This issue has been solved by PR https://github.com/jazzband/django-silk/pull/355, shouldn't it be closed? :)

**Comment by pranavkatiyar** [comment]
Update to django-silk==3.0.4, this will fix the bug.
