### ISSUE TITLE
Enable/disable profiler on-the-fly (without stopping Django)

### ISSUE THREAD

**Issue by utkuyaman** [jazzband/django-silk#40]
It would be useful to have a mechanism to start / stop profiler when it is at production (IMO).
I am not sure if it is possible or not, but a page for authenticated users that disables profiling or may be updating SILKY_INTERCEPT_PERCENT to 100 may be suitable for the task.

**Comment by colsond** [comment]
Just as a note removing silky from installed apps won't work in a production setting. If you try and import the profiler decorator anywhere else after you've removed it from installed apps it throws an error:


```
Traceback (most recent call last):
  File "/opt/cloudscheduler/web_frontend/cloudscheduler/cloudscheduler_web/wsgi.py", line 14, in <module>
     application = get_wsgi_application()
   File "/usr/lib64/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
     return WSGIHandler()
   File "/usr/lib64/python3.6/site-packages/django/core/handlers/wsgi.py", line 140, in __init__
     self.load_middleware()
   File "/usr/lib64/python3.6/site-packages/django/core/handlers/base.py", line 37, in load_middleware
     middleware = import_string(middleware_path)
   File "/usr/lib64/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
     module = import_module(module_path)
   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
   File "/usr/lib/python3.6/site-packages/silk/middleware.py", line 10, in <module>
     from silk.collector import DataCollector
  File "/usr/lib/python3.6/site-packages/silk/collector.py", line 9, in <module>
     from silk import models
   File "/usr/lib/python3.6/site-packages/silk/models.py", line 55, in <module>
     class Request(models.Model):
   File "/usr/lib64/python3.6/site-packages/django/db/models/base.py", line 108, in __new__
     "INSTALLED_APPS." % (module, name)
 RuntimeError: Model class silk.models.Request doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

I've been trying to come up with a way to disable silky in production that doesn't involve scrubbing all the decorators from my function definitions. These are really the only ideas i have left:

1. Wrap the silky profiler decorator in a decorator of my own that conditionally applies the silky decorator.
2. Conditionally import a dummy decorator that does nothing instead of the silky profiler decorator.

**Comment by colsond** [comment]
What I ended up doing is creating a configuration option to remove silky from installed apps and middleware then instead of importing directly from silky I import the "silk_profile" decorator from this file:

```
from functools import wraps

from myapp.lib.csv2_config import Config
config = Config('web_frontend')

if config.enable_profiling:
    from silk.profiling.profiler import silk_profile
else:
    def silk_profile(name=None):
        def s_profile(f):
            @wraps(f)
            def wrapped(*args, **kwargs):
                r = f(*args, **kwargs)
                return r
            return wrapped
        return s_profile

```

**Comment by colonelfitz** [comment]
How about not removing silk from installed apps but removing it from Middlewares?
I think that would work

**Comment by dz0** [comment]
When changing  `SILKY_INTERCEPT_PERCENT` or similar, one needs to deploy&restart, which is not nice **in production**.

Maybe there could be  `SILKY_CONFIG_FETCHER`  -- (path to) function  which fetches configs as dict. By default it would just collect standart settings, that.startswith('SILKY_'). And we could use DB to store settings.
ps.: quick search: seems https://bitbucket.org/jiaaro/django-tupperware/ can do dynamic settings overriding

**Comment by AmirMahmood** [comment]
How about using [jazzband/django-constance](https://github.com/jazzband/django-constance) as an optional solution?
User can change `SILKY_INTERCEPT_PERCENT` or enable/disable silk from admin page.
