### ISSUE TITLE
Clear DB when use sqlite caused OperationalError: too many SQL variables

### ISSUE THREAD

**Issue by eshxcmhk** [jazzband/django-silk#421]
```
Traceback (most recent call last):
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/silk/views/clear_db.py", line 23, in post
    delete_model(SQLQuery)
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/silk/utils/data_deletion.py", line 28, in delete_model
    model.objects.filter(pk__in=items_to_delete).delete()
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/db/models/query.py", line 710, in delete
    collector.collect(del_query)
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/db/models/deletion.py", line 192, in collect
    reverse_dependency=reverse_dependency)
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/db/models/deletion.py", line 88, in add
    if not objs:
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/db/models/query.py", line 278, in __bool__
    self._fetch_all()
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/silk/sql.py", line 58, in execute_sql
    return self._execute_sql(*args, **kwargs)
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1133, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/apis/api_detect_yibing/env/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: too many SQL variables
```

**Comment by eshxcmhk** [comment]
@mtford90  
[https://sqlite.org/limits.html](url) ```Part 9```
*Maximum** Number Of Host Parameters In A Single SQL Statement*

```A host parameter is a place-holder in an SQL statement that is filled in using one of the sqlite3_bind_XXXX() interfaces. Many SQL programmers are familiar with using a question mark ("?") as a host parameter. SQLite also supports named host parameters prefaced by ":", "$", or "@" and numbered host parameters of the form "?123".

Each host parameter in an SQLite statement is assigned a number. The numbers normally begin with 1 and increase by one with each new parameter. However, when the "?123" form is used, the host parameter number is the number that follows the question mark.

SQLite allocates space to hold all host parameters between 1 and the largest host parameter number used. Hence, an SQL statement that contains a host parameter like ?1000000000 would require gigabytes of storage. This could easily overwhelm the resources of the host machine. To prevent excessive memory allocations, the maximum value of a host parameter number is SQLITE_MAX_VARIABLE_NUMBER, which defaults to 999 for SQLite versions prior to 3.32.0 (2020-05-22) or 32766 for SQLite versions after 3.32.0.

The maximum host parameter number can be lowered at run-time using the sqlite3_limit(db,SQLITE_LIMIT_VARIABLE_NUMBER,size) interface.```
