### ISSUE TITLE
_mask_credentials breaks on some html

### ISSUE THREAD

**Issue by lfx** [jazzband/django-silk#423]
Hello guys, awesome tool! Thank you for developing!

I just got some interesting issue with regex in https://github.com/jazzband/django-silk/blob/4.0.1/silk/model_factory.py#L131

```python
body = "csrfmiddlewaretoken=********************&name=breaking&description=&subject=b&content=You%27re+receiving+this+email+because+you+requested+a+password+reset+for+your+user+account.%0D%0A%0D%0AYour+username%2C+in+case+you%27ve+forgotten%3A+%7B%7Buser.get_username%7D%7D%0D%0A%0D%0A%7B%7B+protocol+%7D%7D%3A%2F%2F%7B%7B+domain+%7D%7D%2F%7B%7B+url+%7D%7D&html_content=%3C%21DOCTYPE+html%3E%3Chtml+xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxhtml%22+xmlns%3Av%3D%22urn%3Aschemas-microsoft-com%3Avml%22+xmlns%3Ao%3D%22urn%3Aschemas-microsoft-com%3Aoffice%3Aoffice%22%3E%3Chead%3E%0D%0A++++++++%3Ctitle%3E%0D%0A++++++++++%0D%0A++++++++%3C%2Ftitle%3E&translated_templates-TOTAL_FORMS=0&translated_templates-INITIAL_FORMS=0&translated_templates-MIN_NUM_FORMS=0&translated_templates-MAX_NUM_FORMS=90&translated_templates-__prefix__-language=af&translated_templates-__prefix__-subject=&translated_templates-__prefix__-content=&translated_templates-__prefix__-html_content=&translated_templates-__prefix__-id=&translated_templates-__prefix__-default_template=18&_save=Save"

res[1] = "%3C%21DOCTYPE+html%3E%3Chtml+xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxhtml%22+xmlns%3Av%3D%22urn%3Aschemas-microsoft-com%3Avml%22+xmlns%3Ao%3D%22urn%3Aschemas-microsoft-com%3Aoffice%3Aoffice%22%3E%3Chead%3E%0D%0A++++++++%3Ctitle%3E%0D%0A++++++++++%0D%0A++++++++%3C%2Ftitle%3E"
```
Stack trace:

```
Traceback (most recent call last):
  File "/home/cloud/.local/share/virtualenvs/api-mbQapHxY/lib/python3.8/site-packages/silk/model_factory.py", line 124, in _mask_credentials
    json_body = json.loads(body)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cloud/.local/share/virtualenvs/api-mbQapHxY/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/cloud/.local/share/virtualenvs/api-mbQapHxY/lib/python3.8/site-packages/silk/middleware.py", line 64, in __call__
    self.process_request(request)
  File "/home/cloud/.local/share/virtualenvs/api-mbQapHxY/lib/python3.8/site-packages/silk/profiling/profiler.py", line 55, in wrapped_target
    result = target(*args, **kwargs)
  File "/home/cloud/.local/share/virtualenvs/api-mbQapHxY/lib/python3.8/site-packages/silk/middleware.py", line 107, in process_request
    request_model = RequestModelFactory(request).construct_request_model()
  File "/home/cloud/.local/share/virtualenvs/api-mbQapHxY/lib/python3.8/site-packages/silk/model_factory.py", line 243, in construct_request_model
    body, raw_body = self.body()
  File "/home/cloud/.local/share/virtualenvs/api-mbQapHxY/lib/python3.8/site-packages/silk/model_factory.py", line 222, in body
    raw_body = self._mask_credentials(raw_body)
  File "/home/cloud/.local/share/virtualenvs/api-mbQapHxY/lib/python3.8/site-packages/silk/model_factory.py", line 139, in _mask_credentials
    body = re.sub(
  File "/usr/lib/python3.8/re.py", line 208, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.8/re.py", line 302, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 671, in _parse
    raise source.error("multiple repeat",
re.error: multiple repeat at position 217
```

I'm getting this erorr while saving email template using https://github.com/ui/django-post_office in admin area.

I'm using silk=4.0.1

**Comment by lfx** [comment]
Never mind, it seems that https://github.com/jazzband/django-silk/commit/0cec6a22d12b1f77385ee35c2a335b547e6350e7 fixes regex. Just so far is unreleased.
