### ISSUE TITLE
middleware raising exception in Django 3.2

### ISSUE THREAD

**Issue by daadu** [jazzband/django-silk#496]
I upgrade the following and getting following crash after that:
- Django from 3.0 -> 3.2
- django-silk 4.0.1 -> 4.1.0

```
Creating response model for request model with pk f9470e20-3565-4369-a37d-3fcd196df9b5
Exception when performing meta profiling, dumping trace below
Traceback (most recent call last):
  File "/home/harsh/PycharmProjects/proj/venv/lib/python3.8/site-packages/silk/middleware.py", line 118, in _process_response
    silk_response = ResponseModelFactory(response).construct_response_model()
  File "/home/harsh/PycharmProjects/proj/venv/lib/python3.8/site-packages/silk/model_factory.py", line 302, in construct_response_model
    raw_headers = self.response._headers
AttributeError: 'TemplateResponse' object has no attribute '_headers'
Retrying _process_response
Process response
Creating response model for request model with pk f9470e20-3565-4369-a37d-3fcd196df9b5
Exception when performing meta profiling, dumping trace below
Traceback (most recent call last):
  File "/home/harsh/PycharmProjects/proj/venv/lib/python3.8/site-packages/silk/middleware.py", line 139, in process_response
    self._process_response(request, response)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/harsh/PycharmProjects/proj/venv/lib/python3.8/site-packages/silk/middleware.py", line 118, in _process_response
    silk_response = ResponseModelFactory(response).construct_response_model()
  File "/home/harsh/PycharmProjects/proj/venv/lib/python3.8/site-packages/silk/model_factory.py", line 302, in construct_response_model
    raw_headers = self.response._headers
AttributeError: 'TemplateResponse' object has no attribute '_headers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/harsh/PycharmProjects/proj/venv/lib/python3.8/site-packages/silk/middleware.py", line 118, in _process_response
    silk_response = ResponseModelFactory(response).construct_response_model()
  File "/home/harsh/PycharmProjects/proj/venv/lib/python3.8/site-packages/silk/model_factory.py", line 302, in construct_response_model
    raw_headers = self.response._headers
AttributeError: 'TemplateResponse' object has no attribute '_headers'
```

**Comment by daadu** [comment]
Ok looks like the issue is no more with "master" branch. Forgot that v4.1.0 does not support Django 3.2.


Closing this.
