### ISSUE TITLE
Attempt to access queries without initialisation. Is the middleware installed correctly?

### ISSUE THREAD

**Issue by Joish** [jazzband/django-silk#569]
I am getting this error when trying to silk_profile decorator  .i.e. `@silk_profile(name='...')`

backend_1             | Exception when performing meta profiling, dumping trace below
backend_1             | Traceback (most recent call last):
backend_1             |   File "/usr/local/lib/python3.9/site-packages/silk/profiling/profiler.py", line 159, in wrapped_target
backend_1             |     self._start_queries()
backend_1             |   File "/usr/local/lib/python3.9/site-packages/silk/profiling/profiler.py", line 78, in _start_queries
backend_1             |     self._queries_before = self._query_identifiers_from_collector()
backend_1             |   File "/usr/local/lib/python3.9/site-packages/silk/profiling/profiler.py", line 74, in _query_identifiers_from_collector
backend_1             |     return [x for x in DataCollector().queries]
backend_1             |   File "/usr/local/lib/python3.9/site-packages/silk/collector.py", line 67, in queries
backend_1             |     return self._get_objects(TYP_QUERIES)
backend_1             |   File "/usr/local/lib/python3.9/site-packages/silk/collector.py", line 76, in _get_objects
backend_1             |     self._raise_not_configured(
backend_1             |   File "/usr/local/lib/python3.9/site-packages/silk/collector.py", line 99, in _raise_not_configured
backend_1             |     raise SilkNotConfigured(err + ' Is the middleware installed correctly?')
backend_1             | silk.errors.SilkNotConfigured: Attempt to access queries without initialisation. Is the middleware installed correctly?
backend_1             | Attempt to access queries without initialisation. Is the middleware installed correctly?

in my setting page
`SILKY_PYTHON_PROFILER = True`
`SILKY_META = True`

Added silk in app section
`silk`

Added middleware
`'silk.middleware.SilkyMiddleware',`

FTR, Also I have tried placing the silk middleware in different indexes in the MIDDLEWARE list on Django setting page.
Can someone please help me if I am missing any step or doing something wrong?

**Comment by SebCorbin** [comment]
Can you paste the function you are decorating?
